### ISSUE TITLE
Remove console.log

### ISSUE THREAD

**Issue by supermomme** [Nafaya/esphome-native-api#1]
Got some output from that package, while i use it. And it is a bit anoying. Could you remove console.log´s or a option to opt-out of it?

**Comment by jfirwin** [comment]
I've been fiddling with this as well. I agree with @supermomme that the console.logs should be more in line with the package `subscribeLogsService` where you can specify granularity.

**Comment by Nafaya** [comment]
Hello.
my fault)  There is already rolled out new version without logs.

Thank you for this feedback. I supposed no one is using the package.
Feel free to suggest any improvements you may need
