### ISSUE TITLE
Incorrect error when connection fails

### ISSUE THREAD

**Issue by DutchmanNL** [Nafaya/esphome-native-api#11]
When I try to connect to an device which is not reachable, I receive in on('Error') 
`Error: connect ECONNREFUSED 127.0.0.1:6053`

Which is strange as the IP is not 127.0.0.1 somehow it return the wrong IP or try to use the wrong IP if connection cannot be established

**Comment by Nafaya** [comment]
Hey,
I cannot reproduce your case. If I put not reachable IP or hostname I get an appropriate error.
Could you, please, check the connection options?

**Comment by DutchmanNL** [comment]
solved by latest version, I assume it had something todo with the entity part :)
