### ISSUE TITLE
Empty error message for incorrect password

### ISSUE THREAD

**Issue by DutchmanNL** [Nafaya/esphome-native-api#12]
After changing library to 1.0.9 (update from 1.0.7) I get only {} as error if I provide an incorrect password.
Before 1.0.9 I got a proper error messaging stating incorrect password

**Comment by Nafaya** [comment]
That's strange. Error logic didn't change.
Let me guess... Are you using JSON.stringify on Error instance?
```
client.on('error', error => {
    console.log(JSON.stringify(error));
});
```

**Comment by DutchmanNL** [comment]
My mistake, I did check on the error and not error.message :/
