### ISSUE TITLE
List state of entity

### ISSUE THREAD

**Issue by DutchmanNL** [Nafaya/esphome-native-api#7]
Would it be possible to implement a function (or have it in the listEntities part) to also have the current value submitted ?
Reason : Currently I can only see what kind of state is in the entities when a state change or update is handle and fired by the API.

Wanted situation : Having a proper JSON array including the state value at first initialization

Reason : ensure proper initialization of the module with current value of state before an event occurs

**Comment by Nafaya** [comment]
Hey.

ListEntities function just calls the corresponding service of esp device. Under the hood, the service after receiving the list of entities request sends a group of messages describing its entities, and then the service sends a "done" message to notify that the list is finished. The nature of service is "request-response".
But for states, we have just events. We cannot be sure when we will receive the state event or even will this event be emitted or not. Also, you must notify the esp device that you want to receive state changes(It is a separate esp service).

I do not want to add sophisticated logic to this library and prefer to provide esp function as straight as possible.

In your case, the `state` event of any entity might be helpful: after receiving a new entity, you can check `state` property: whether it is defined or not. If not subscribe to the `state` event of the entity, add timeouts and other logic according to your needs.

I know it's a bit sophisticated, but again, I think such logic is out of the scope of the purpose of this library.

I'm not completely sure that I correctly understand your case. If I am wrong, please, provide more details about the case.

Thank you for your insights, I appreciate it.

**Comment by DutchmanNL** [comment]
Perfect THANK YOU ! I didn't noticed I can call the state directly, so this solves my issue.
I just added the call *.state in my logic after the entity has be initialized successfully and by that I am always having the current value of the state.

Keep up the great work, I appreciate this module very much. I wanted to have an native ESPHome integration to my NodeJS framework application and basically started working om sone kind of layer between. This modules allows me now to embedded the code by the module, saves me A LOT OF WORK and I can focus on my project.

If you would be anywhere in the neighbor, you would get one of he best whiskeys I have here at my House ! :)

Have a nice day, I will keep raising issue for questions or suggestion and if you need feedback feel free to contact me
