### ISSUE TITLE
discovery

### ISSUE THREAD

**Issue by DutchmanNL** [Nafaya/esphome-native-api#8]
would it be possible to implement discovery of devices?

**Comment by Nafaya** [comment]
yes, I will add somethings based on this code later:


```
const MdnsDiscovery = require('mdns-discovery');

var mdnsDiscovery = new MdnsDiscovery({});
mdnsDiscovery.on('packet', function (packet, rinfo) {
    const packet = parseEsphomePacket(packet, rinfo);
    if (packet) {
        console.log(packet);
    }
});
mdnsDiscovery.run ();

function parseEsphomePacket(packet, rinfo) {
    if (!packet.answers) return null;
    const ptr = packet.answers.find(({ type, name }) => type === 'PTR' && name === '_esphomelib._tcp.local');
    if (!ptr) return null;
    const txt = packet.answers.find(({ type, name }) => type === 'TXT' && name === ptr.data);
    if (!txt) return null;

    const txtdataregexp = /^\u0010mac=(.+)\u001eaddress=(.+\.local)\u000eversion=(.+)$/;
    const match = txtdataregexp.exec(txt.data.toString());
    if (!match) return null;
    
    return {
        mac: match[1],
        host: match[2],
        version: match[3],
        ...rinfo
    }
}
```

But 2 things:
- mdns is supported by some routers.
- there is no way to query mdns. What the code above does is that it listens to the udp multicast address, decode and filter received messages. We have to wait until esphome home device says "Hello, that me". This happens on startup and also I suppose there is an interval between publishing(not sure about it, maybe my esp32 just decided to reboot or renew its wifi connection).

**Comment by DutchmanNL** [comment]
i tried to play around a little with MDNS : 

"there is no way to query mdns"

ageren, what I noticed is when the MDSN browser starts up basically all clients respond. So I think there will be 2 situations : 

- starting the MDNS browser causing a broadcast
- device started sending a broadcast

**Comment by Nafaya** [comment]
Which library are you using?

`mdns-discovery` after start just listens to messages.

**Comment by DutchmanNL** [comment]
you can have a look at mdns-js, its not maintained for a while that's why I not used it but the code below gives you feedback at every run of all : 


```

var mdns = require('mdns-js');
//if you have another mdns daemon running, like avahi or bonjour, uncomment following line
//mdns.excludeInterface('0.0.0.0');

var browser = mdns.createBrowser();

browser.on('ready', function () {
    browser.discover(); 
});

browser.on('update', function (data) {
    console.log(`data: ${JSON.stringify(data)}`);
});
```

edit : And this is the JSON response for an ESPHome device : 

```
{
  "addresses": [
    "192.168.178.38"
  ],
  "query": [
    
  ],
  "type": [
    {
      "name": "esphomelib",
      "protocol": "tcp",
      "subtypes": [
        
      ]
    }
  ],
  "interfaceIndex": 1,
  "networkInterface": "pseudo multicast"
}
```

**Comment by DutchmanNL** [comment]
and here a. simpler version based on mdns-discovery which scans every 30 seconds :)

```
var Mdns = require('mdns-discovery');
 
var mdns = new Mdns({ 
    timeout: 10,
        name: [
            '_esphomelib._tcp.local',
    ],
    find: '*',
});

mdns.on('packet', function (packets, rinfo) {
    console.log(`ESPHome device found at IP ${JSON.stringify(rinfo.address)}`)
});

function mdnsRun(){
    mdns.run();
    timeout = setTimeout(async function () {
        mdnsRun()
    }, 10000);
}

// Scan for devices
mdnsRun()
```

**Comment by Nafaya** [comment]
Thanks,
Finally, I added discovery. You can check the docs : )
